config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  get '/ask', to: 'questions#ask'
  get '/answer', to: 'questions#answer'

  # root "articles#index"


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def ask
  end

  def answer
    @input = params[:input]
    if @input == 'I am going to work'
      @answer = 'Great!'
    elsif @input.include?('?')
      @answer = 'Silly question, get dressed and go to work!'
    else
      @answer = "I don't care, get dressed and go to work!"
    end
  end
end

#  coach (poor) logic, here it is:

# If the message is I am going to work, the coach will answer Great!
# If the message has a question mark ? at the end, the coach will answer Silly question, get dressed and go to work!.
# Otherwise the coach will answer I don't care, get dressed and go to work!

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsStupidCoaching</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/questions/answer.html.erb
<%# <%= link_to "Stupid Coach", answer_path %>


<html>
  <head>
    <title>First Stupid Coach</title>
  </head>

  <body>
    <%# <%= yield %>
    <h2>First Stupid Coach</h2>
    <p>Your Question is: <%= @input%></p>
    <p><%= @answer%></p>
    <%= link_to "Ask me another question?", ask_path %>
  </body>
</html>

app/views/questions/ask.html.erb
<html>
  <head>
    <title>First Stupid Coach</title>
  </head>

  <body>
    <h2>First Stupid Coach</h2>
    <form action="/answer" data-turbo="false" class="row g-3">
      <div class="input-group mb-3">
        <input type="text" name="input" value="<%= params[:input] %>"
          class="col-2 form-control" placeholder="Ask the coach."
          aria-label="Ask the coach" aria-describedby="button-addon2">
        <div class="col-2 input-group-append">
          <button input type="submit" value="Ask!"
            class="btn btn-outline-secondary" type="button" id="button-addon2">
            Here we Go!</button>
        </div>
      </form>
    </div>

  <%= yield %>
  </body>
</html>